name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Build da aplicação
        # Substitua NOME_DO_REPOSITORIO pelo nome do seu projeto no GitHub
        run: npx ng build --configuration production --base-href /lol-build-pro/

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/app/browser # Baseado no nome do seu projeto "app" no angular.json
          branch: gh-pages
